# Default compile flags.
CFLAGS=-Os -g

# Kernel path
RAVENSCAR_SRC=/home/lego/Documents/gnatmindstorms2011/lib/gcc/arm-eabi/4.5.3/rts-ravenscar-sfp/ravenscar

# Main subprogram.
PRG=helloworld

include $(RAVENSCAR_SRC)/Makefile.inc
